{
  imports = [
    ./brave.nix
    ./brightnessctl.nix
    ./devenv.nix
    ./dolphin.nix
    ./ffmpeg.nix
    ./freerdp.nix
    ./imagemagick.nix
    ./libreoffice.nix
    ./nixfmt.nix
    ./ocaml.nix
    ./packettracer.nix
    ./pavucontrol.nix
    ./slack.nix
    ./typst.nix
    ./wireshark.nix
    ./xournalpp.nix
    ./zen-browser.nix
  ];
}
